In [205]:
# !nvidia-smi

In [104]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


Introduction  to tensors:

> Creating Tensors



PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [105]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [106]:
scalar.ndim

0

In [107]:

# Get tensor back as Python int
scalar.item()

7

In [108]:
# Vector
vector = torch.tensor([7, 7,34])
vector

tensor([ 7,  7, 34])

In [109]:
vector.ndim

1

In [110]:
vector.shape

torch.Size([3])

In [111]:
# MATRIX
MATRIX = torch.tensor([
    [7, 8],
    [9, 23]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 23]])

In [112]:
MATRIX.ndim

2

In [113]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 23]))

In [114]:
MATRIX.shape

torch.Size([2, 2])

In [115]:
# TENSOR
TENSOR = torch.tensor([[
                [1, 2, 3],
                [4, 5, 6],
                [6, 4, 45]
]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 6,  4, 45]]])

In [116]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  4, 45]])

In [117]:
TENSOR.shape

torch.Size([1, 3, 3])

In [118]:
TENSOR.ndim

3

In [119]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [120]:
x.shape

torch.Size([2, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
Start with  random numbers -> look at data -> update random numbers -> look at data -> update random  numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [121]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [122]:
random_tensor.ndim

2

In [123]:
random_tensor.shape


torch.Size([3, 4])

In [124]:
# Create a random tensor with simialr shape to an image tensor
random_image_size_tensor =  torch.rand(size=(224, 224, 3)) #height, width , colour channel(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [125]:

# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [126]:

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [127]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [128]:
one_to_ten = torch.arange(start=1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
# Creatin tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors Datatypes
Note: Tensor datatypes is one of the 3 big erros you'll run into PyTorch & deep learning
1. Tensors not rigt datatype
2. Tensors not right shape
3. Tensors not on the right device


In [130]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,
                               device= None,
                            requires_grad=False)

float_32_tensor

tensor([3., 6., 9.])

In [131]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [132]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [133]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [134]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting attributes from tensors

1. Tensors not rigt datatype--> to get data type use `tensor.dtype`
2. Tensors not right shape--> to get shape of tensor use `tensor.shape`
3. Tensors not on the right device --> to get device on which tensors are running use `tensor.device`

In [135]:
# Create a tensor
some_tensor= torch.rand(3, 4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [136]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:  {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Datatype of tensor:  torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor : cpu


### Manipulating Tensors (tensor operation)

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Divison
*Matrix Multiplication

In [137]:
# Create  A tensor
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10

In [138]:
tensor

tensor([11, 12, 13])

In [139]:
# Multiply the tensor
tensor = tensor * 20
tensor



tensor([220, 240, 260])

In [140]:
# Subtract the tensor
tensor = tensor - 10
tensor

tensor([210, 230, 250])

In [141]:
# Try out Pytorch built in funciton
tensor = torch.mul(tensor, 2)
tensor

tensor([420, 460, 500])

In [142]:
tensor = torch.add(tensor, 2)
tensor

tensor([422, 462, 502])

### Matric MULTIPLICATION
Toe main ways of performing multiplication in neural network and deep learning.
1. Element wise multiplication

*   List item
*   List item


2. Matrix multiplication



There are two rules that performing matirx multiplication needs to satisfy;
1. The **inner dimensions** must match


*   (3, 2) @ (3, 2) won't work
*   (2, 3) @ (3, 2) will work


*   (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of outer dimensions


*  (2, 3) @ (3, 2) -> (2, 2)










In [143]:
tensor = torch.tensor([1, 2, 3])

In [144]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [145]:
# Matrix Multiplicatin
torch.matmul(tensor, tensor)

tensor(14)

In [146]:
%%time
value  = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 0 ns, sys: 797 µs, total: 797 µs
Wall time: 695 µs


In [147]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 163 µs, sys: 32 µs, total: 195 µs
Wall time: 164 µs


tensor(14)

### One of the most common errors in deep learning

In [148]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

In [149]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor issues , we can maipulate the shape of one of our tensors using  A *transpose* switches the axes of dimensions

In [150]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [151]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [152]:
# The mtrix multiplication operaration works when tensor B is transposed.
print(f"Orignal shapes: tensor_A {tensor_A.shape}, tensor_B ={tensor_B.shape}")
print(f"New Shapes : tensor_A: {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplication: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Orignal shapes: tensor_A torch.Size([3, 2]), tensor_B =torch.Size([3, 2])
New Shapes : tensor_A: torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplication: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggregation)

In [153]:
# create a tesnor

x = torch.arange(3, 100, 10)
x, x.dtype

(tensor([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93]), torch.int64)

In [154]:
# find the min
torch.min(x)

tensor(3)

In [155]:
x.min()

tensor(3)

In [156]:
# find max
torch.max(x), x.max()

(tensor(93), tensor(93))

In [157]:
# Find mean --note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(48.), tensor(48.))

In [158]:
# Find Sum
torch.sum(x)

tensor(480)

In [159]:
# find the positon in tensor that has minimum value  with argmin() returns index of the minimum value in tensor
x.argmin()


tensor(0)

In [160]:
x[0]

tensor(3)

In [161]:
# find the positon in tensor that has maximum value  with argmax() returns index of the maximum value in tensor
x.argmax()


tensor(9)

In [162]:
x[9]

tensor(93)

### Reshaping , stacking, squeezing, and unsqueezing tensors


Reshaping- reshapes an input tensor to a defined shape
View-Return a view of an input tensor of =certain but keep the same memory as the orginal tensor
Stacking- combine multiple tensors on top of each other (vstack) or side by side hstack
Squeeze-> removes all 1 dimensions form a tensor
Unsqueeze-> Add a 1 dimension to a target tensor
Permute--> Return a view of the input with dimension permuted (swapped) in a certain way





In [163]:
# create tensor
x2 = torch.arange(1., 10.)
x2, x2.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [164]:
# Add an extra dimension
x2_reshaped = x2.reshape(1, 9)
x2_reshaped, x2_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [165]:
x2_reshaped = x2.reshape(9, 1)
x2_reshaped, x2_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [166]:
#changing the view
z = x2.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

# Changing z changes x (because a view of a tensor shares the same memory as the orignal)

In [167]:
z[:, 0] = 5
z, x2

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [168]:
# stack tensors on top of each other
x_stacked = torch.stack([x2, x2, x2], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [169]:
# torch.squeeze() -removes all single dimensions from a target tensor
print(f"previous tesnor: {x2_reshaped}")

previous tesnor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [170]:
print(f"previous shape: {x2_reshaped.shape}")
x2_reshaped.shape

previous shape: torch.Size([9, 1])


torch.Size([9, 1])

In [171]:
# Remove extra dimensions from x2_reshaped
x2_squeezed = x2_reshaped.squeeze()
print(f"\nNew tensor: {x2_squeezed}")
print(f"New shape: {x2_squeezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [172]:
# torch.unsqueezed() -adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target: {x2_squeezed}")
print(f"previous shape: {x2_squeezed.shape}")

# Add an extra dimension with unsqueeze
x2_unsqueezed = x2_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x2_unsqueezed}")
print(f"\nNew Shape : {x2_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New Shape : torch.Size([1, 9])


In [173]:
# torch.permute --mean rearrange

x_orignal = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the orignal tensor to rearrange the axis or dim order
x_permuted = x_orignal.permute(2, 0, 1) # shifts 0>1, 1>2, 2>0

print(f"Previous shape:{x_orignal.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape:torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


###Indexing(Selecting data from tensors)
Indexing with Pytorch is similar to indexing wit NumPy

In [174]:
x_tensor = torch.arange(1,10).reshape(1, 3, 3)
x_tensor, x_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [175]:
# Let's find on our new tensor
x_tensor[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [176]:
# Let's index on the middle bracket (dim=1)
x_tensor[0][0], x_tensor[0, 1], x_tensor[0, 2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [177]:
# Let's index on the most inner bracket (last dimension)
x_tensor[0][0][0],x_tensor[0][0][1], x_tensor[0][0][2]


(tensor(1), tensor(2), tensor(3))

In [178]:
x_tensor[0][1][0],x_tensor[0][1][1], x_tensor[0][1][2]

(tensor(4), tensor(5), tensor(6))

In [179]:
x_tensor[0][2][0],x_tensor[0][2][1], x_tensor[0][2][2]

(tensor(7), tensor(8), tensor(9))

In [180]:
# we can also use ": " to slect "all" of target dimension
x_tensor[:, 0]

tensor([[1, 2, 3]])

In [181]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x_tensor[:, :, 1]

tensor([[2, 5, 8]])

In [182]:
# get all values of dimension and 1st dimensions but only the 1 index value of 1st and 2nd dimension
x_tensor[:, 1, 1]

tensor([5])

In [183]:
# get index 0  of 0th  and 1st dimensions all values of 2nd dimension
x_tensor[0,0, :]

tensor([1, 2, 3])

In [184]:
#index to return 3, 6, 9
print(x_tensor[:, : , 2])

tensor([[3, 6, 9]])


### Pytorch and Numpy
Numpy is a popular scientific Python numerical computing library
And because of this, pytorch has funcitonality to interact with it
* Data in Numpy, want in PyTorch tensor --> `torch.from_numpy(ndarray)`
* PyTorch tensor-> Numpy-> torch.Tensor.numpy()

In [185]:
# Numpy array to tensor
import numpy as np

array  = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [186]:
array.dtype

dtype('float64')

In [187]:
tensor.dtype

torch.float64

In [188]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [189]:
# Change the value of array what will this do to `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [190]:
# Tensor to NUMPY ARRAY
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [191]:
numpy_tensor.dtype

dtype('float32')

In [192]:
# change the tensor, what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

inshort how a neural network learns:
'start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again ->again -> again ....'

To reduc the randomness in neural network and Pytorch comes the concpet of a random seed.

Essentially what random seed does is "flaour" the radomness.

In [193]:
torch.rand(3, 3)

tensor([[0.5888, 0.8403, 0.4761],
        [0.7140, 0.4644, 0.6362],
        [0.8892, 0.1317, 0.7164]])

In [194]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2706, 0.6560, 0.6614, 0.3648],
        [0.1490, 0.8693, 0.0294, 0.5449],
        [0.0794, 0.2313, 0.2927, 0.3386]])
tensor([[0.3708, 0.0831, 0.0944, 0.6568],
        [0.7708, 0.1053, 0.1467, 0.1932],
        [0.9118, 0.1488, 0.0913, 0.4470]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [195]:
# set the manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C  = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)


print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [196]:
# Different ways of accessing GPU in PyTorch


In [197]:
!nvidia-smi

Thu Aug 20 05:32:49 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   61C    P0             28W /   70W |     107MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [198]:
# Checking GPU access with Pytorch
torch.cuda.is_available()

True

In [199]:
# setting up device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [200]:
# counting the number of devices
torch.cuda.device_count()

1

In [201]:
# Setting up GPU devices on and off devices
# Putting tensors and models on GPU
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [202]:
# MOVE tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [203]:
## Moving tensor back to cpu
# if tensor is on gpu can't transform it to numpy
#tensor_on_gpu.numpy()

In [204]:
# To fix gpu tensro with NUMPY issues, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])