In [273]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [274]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [275]:
df.shape

(569, 33)

In [276]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [277]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [278]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [279]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
197,18.080,21.84,117.40,1024.0,0.07371,0.08642,0.11030,0.057780,0.1770,0.05340,...,19.76,24.70,129.10,1228.0,0.08822,0.19630,0.2535,0.09181,0.2369,0.06558
488,11.680,16.17,75.49,420.5,0.11280,0.09263,0.04279,0.031320,0.1853,0.06401,...,13.32,21.59,86.57,549.8,0.15260,0.14770,0.1490,0.09815,0.2804,0.08024
396,13.510,18.89,88.10,558.1,0.10590,0.11470,0.08580,0.053810,0.1806,0.06079,...,14.80,27.20,97.33,675.2,0.14280,0.25700,0.3438,0.14530,0.2666,0.07686
548,9.683,19.34,61.05,285.7,0.08491,0.05030,0.02337,0.009615,0.1580,0.06235,...,10.93,25.59,69.10,364.2,0.11990,0.09546,0.0935,0.03846,0.2552,0.07920
474,10.880,15.62,70.41,358.9,0.10070,0.10690,0.05115,0.015710,0.1861,0.06837,...,11.94,19.35,80.78,433.1,0.13320,0.38980,0.3365,0.07966,0.2581,0.10800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,17.350,23.06,111.00,933.1,0.08662,0.06290,0.02891,0.028370,0.1564,0.05307,...,19.85,31.47,128.20,1218.0,0.12400,0.14860,0.1211,0.08235,0.2452,0.06515
566,16.600,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.053020,0.1590,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.14180,0.2218,0.07820
300,19.530,18.90,129.50,1217.0,0.11500,0.16420,0.21970,0.106200,0.1792,0.06552,...,25.93,26.24,171.10,2053.0,0.14950,0.41160,0.6121,0.19800,0.2968,0.09929
434,14.860,16.94,94.89,673.7,0.08924,0.07074,0.03346,0.028770,0.1573,0.05703,...,16.31,20.54,102.30,777.5,0.12180,0.15500,0.1220,0.07971,0.2525,0.06827


In [280]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
340,14.42,16.54,94.15,641.2,0.09751,0.11390,0.08007,0.04223,0.1912,0.06412,...,16.67,21.51,111.40,862.1,0.12940,0.3371,0.3755,0.14140,0.3053,0.08764
211,11.84,18.94,75.51,428.0,0.08871,0.06900,0.02669,0.01393,0.1533,0.06057,...,13.30,24.99,85.22,546.3,0.12800,0.1880,0.1471,0.06913,0.2535,0.07993
447,14.80,17.66,95.88,674.8,0.09179,0.08890,0.04069,0.02260,0.1893,0.05886,...,16.43,22.74,105.90,829.5,0.12260,0.1881,0.2060,0.08308,0.3600,0.07285
528,13.94,13.17,90.31,594.2,0.12480,0.09755,0.10100,0.06615,0.1976,0.06457,...,14.62,15.38,94.52,653.3,0.13940,0.1364,0.1559,0.10150,0.2160,0.07253
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,17.06,28.14,110.60,897.0,0.16540,0.3682,0.2678,0.15560,0.3196,0.11510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,12.10,17.72,78.07,446.2,0.10290,0.09758,0.04783,0.03326,0.1937,0.06161,...,13.56,25.80,88.33,559.5,0.14320,0.1773,0.1603,0.06266,0.3049,0.07081
243,13.75,23.77,88.54,590.0,0.08043,0.06807,0.04697,0.02344,0.1773,0.05429,...,15.01,26.34,98.00,706.0,0.09368,0.1442,0.1359,0.06106,0.2663,0.06321
376,10.57,20.22,70.15,338.3,0.09073,0.16600,0.22800,0.05941,0.2188,0.08450,...,10.85,22.82,76.51,351.9,0.11430,0.3619,0.6030,0.14650,0.2597,0.12000
195,12.91,16.33,82.53,516.4,0.07941,0.05366,0.03873,0.02377,0.1829,0.05667,...,13.88,22.00,90.81,600.6,0.10970,0.1506,0.1764,0.08235,0.3024,0.06949


In [281]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [282]:
X_train

array([[ 1.10491411,  0.52887325,  1.02784502, ..., -0.36539838,
        -0.8898801 , -1.04152148],
       [-0.69843278, -0.77503889, -0.6837251 , ..., -0.27054152,
        -0.20404152, -0.24456411],
       [-0.18278828, -0.14952901, -0.16874301, ...,  0.4349002 ,
        -0.4216179 , -0.42831008],
       ...,
       [ 1.51348489, -0.14722934,  1.52199912, ...,  1.22337907,
         0.0545275 ,  0.79104558],
       [ 0.1976052 , -0.5979644 ,  0.10855503, ..., -0.54643432,
        -0.6439242 , -0.89528578],
       [-0.3659407 , -0.35419952, -0.3692634 , ..., -0.55316706,
        -0.24345753, -0.30218858]])

In [283]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test= encoder.fit_transform(y_test)

In [284]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor =torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [285]:
import torch.nn as nn

In [286]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, num_features):
    out = self.linear(num_features)
    out = self.sigmoid(out)
    return out


In [287]:
loss_function= nn.BCELoss()


In [288]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [289]:
learning_rate = 0.01

In [290]:
epochs = 250

In [291]:
# create model
model = MySimpleNN(num_features=X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for epoch in range(epochs):
  y_pred= model(X_train_tensor)

  # loss functions
  loss =loss_function(y_pred, y_train_tensor.view(-1, 1))
  optimizer.zero_grad()
  # backward pass
  loss.backward()

 # optimzer
  optimizer.step()



  print(f'Epoch: {epoch  + 1} Loss: {loss.item()}')



Epoch: 1 Loss: 1.0098155736923218
Epoch: 2 Loss: 0.9721969366073608
Epoch: 3 Loss: 0.9364790320396423
Epoch: 4 Loss: 0.9026359915733337
Epoch: 5 Loss: 0.87063068151474
Epoch: 6 Loss: 0.8404157161712646
Epoch: 7 Loss: 0.8119344115257263
Epoch: 8 Loss: 0.7851215600967407
Epoch: 9 Loss: 0.7599055767059326
Epoch: 10 Loss: 0.7362098097801208
Epoch: 11 Loss: 0.7139535546302795
Epoch: 12 Loss: 0.6930540204048157
Epoch: 13 Loss: 0.6734276413917542
Epoch: 14 Loss: 0.6549912691116333
Epoch: 15 Loss: 0.6376637816429138
Epoch: 16 Loss: 0.6213664412498474
Epoch: 17 Loss: 0.6060242652893066
Epoch: 18 Loss: 0.5915664434432983
Epoch: 19 Loss: 0.5779266953468323
Epoch: 20 Loss: 0.5650432705879211
Epoch: 21 Loss: 0.5528595447540283
Epoch: 22 Loss: 0.5413230061531067
Epoch: 23 Loss: 0.5303858518600464
Epoch: 24 Loss: 0.520004153251648
Epoch: 25 Loss: 0.5101378560066223
Epoch: 26 Loss: 0.5007504820823669
Epoch: 27 Loss: 0.4918084740638733
Epoch: 28 Loss: 0.48328137397766113
Epoch: 29 Loss: 0.4751413464546

In [292]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.2866,  0.0893,  0.3605,  0.2850,  0.2388,  0.2911,  0.1357,  0.1525,
          -0.0226, -0.0808,  0.1767,  0.0290,  0.1002,  0.1332,  0.1054, -0.0972,
           0.0509,  0.0069, -0.0870, -0.0530,  0.2528,  0.1460,  0.3322,  0.1531,
           0.0485,  0.3162,  0.0988,  0.3483,  0.2413, -0.0244]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0237], requires_grad=True))

In [293]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.6218836307525635


In [294]:
class MultiLayerNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, num_features):
    out = self.network(num_features)
    return out

In [295]:
learning_rate = 0.1
epochs = 25


In [296]:
loss_function = nn.BCELoss()

In [297]:
# model creation

model = MultiLayerNN(num_features=X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
  y_pred = model(X_train_tensor)

  # calculate loss
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # clear gradients

  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # optimizer

  optimizer.step()

  print(f'Epoch: {epoch +  1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.7127346992492676
Epoch: 2, Loss: 0.7041569352149963
Epoch: 3, Loss: 0.6970515847206116
Epoch: 4, Loss: 0.691001832485199
Epoch: 5, Loss: 0.685539186000824
Epoch: 6, Loss: 0.680823028087616
Epoch: 7, Loss: 0.6768814921379089
Epoch: 8, Loss: 0.6734201908111572
Epoch: 9, Loss: 0.6703484654426575
Epoch: 10, Loss: 0.6674447655677795
Epoch: 11, Loss: 0.6646389365196228
Epoch: 12, Loss: 0.6618627905845642
Epoch: 13, Loss: 0.6589930057525635
Epoch: 14, Loss: 0.6560086607933044
Epoch: 15, Loss: 0.6525481343269348
Epoch: 16, Loss: 0.6485280394554138
Epoch: 17, Loss: 0.6438613533973694
Epoch: 18, Loss: 0.6379188895225525
Epoch: 19, Loss: 0.630275309085846
Epoch: 20, Loss: 0.6222107410430908
Epoch: 21, Loss: 0.6132511496543884
Epoch: 22, Loss: 0.6030568480491638
Epoch: 23, Loss: 0.5919068455696106
Epoch: 24, Loss: 0.5799190998077393
Epoch: 25, Loss: 0.5671172142028809


In [298]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(accuracy)

tensor(0.7105)
