In [150]:
import pandas as pd
df= pd.read_csv('/content/100_Unique_QA_Dataset.csv')
df.head()

,question,answer
0,What is the capital of France?,Paris
1,What is the capital of Germany?,Berlin
2,Who wrote 'To Kill a Mockingbird'?,Harper-Lee
3,What is the largest planet in our solar system?,Jupiter
4,What is the boiling point of water in Celsius?,100


In [151]:
# tokenize the words

def tokenize(text):
  text= text.lower()
  text= text.replace('?', '')
  text= text.replace("'", "")
  return text.split()

In [152]:
text= "My name is Muhamad Idrees. I am a Computer sicence graduate and I am a good programmer and problem solver with hands on practice in Data structure. "
tokenize(text)

['my',
 'name',
 'is',
 'muhamad',
 'idrees.',
 'i',
 'am',
 'a',
 'computer',
 'sicence',
 'graduate',
 'and',
 'i',
 'am',
 'a',
 'good',
 'programmer',
 'and',
 'problem',
 'solver',
 'with',
 'hands',
 'on',
 'practice',
 'in',
 'data',
 'structure.']

In [153]:
# vocabulary
vocab= {'<UNK>':0}

In [154]:
def vocabulary(row):
  tokenized_question= tokenize(row['question'])
  tokenized_answer= tokenize(row['answer'])
  merged_tokens= tokenized_question + tokenized_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token]= len(vocab)

  return merged_tokens




In [155]:
vocab

{'<UNK>': 0}

In [156]:
df.apply(vocabulary, axis=1)

,0
0,"[what, is, the, capital, of, france, paris]"
1,"[what, is, the, capital, of, germany, berlin]"
2,"[who, wrote, to, kill, a, mockingbird, harper-..."
3,"[what, is, the, largest, planet, in, our, sola..."
4,"[what, is, the, boiling, point, of, water, in,..."
...,...
85,"[who, directed, the, movie, titanic, jamescame..."
86,"[which, superhero, is, also, known, as, the, d..."
87,"[what, is, the, capital, of, brazil, brasilia]"
88,"[which, fruit, is, known, as, the, king, of, f..."


In [157]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'unit

In [158]:
len(vocab)

324

In [159]:
from numpy import index_exp
# convertin the words into numerical unique vectors
def text_to_indices(text, vocab):
  index_text= []
  for token in tokenize(text):
    if token in vocab:
      index_text.append(vocab[token])
    else:
      index_text.append(vocab['<UNK>'])

  return index_text

In [160]:
text_to_indices("What is the Idrees", vocab=vocab)

[1, 2, 3, 0]

In [161]:
import torch
from torch.utils.data import Dataset, DataLoader

class QADataset(Dataset):


  def __init__(self, df, vocab):
    self.df= df
    self.vocab= vocab

  def __len__(self):
    return len(self.df)

  def __getitem__(self, index):
    numerical_question= text_to_indices(self.df.iloc[index]['question'], self.vocab)

    numerical_answer= text_to_indices(self.df.iloc[index]['answer'], self.vocab)


    return torch.tensor(numerical_question), torch.tensor(numerical_answer)



In [162]:
dataset= QADataset(df, vocab)

In [163]:
print(dataset)

In [164]:
dataset[0], dataset[0][0]

((tensor([1, 2, 3, 4, 5, 6]), tensor([7])), tensor([1, 2, 3, 4, 5, 6]))

In [165]:
dataloader= DataLoader(dataset, batch_size= 1, shuffle=True)
print(dataloader)

In [166]:
for question, answer in dataloader:
  print(question, answer)

tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[ 42, 318

In [167]:
import torch.nn as nn


In [168]:
from IPython.terminal import embed
class SimpleRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()

    self.embedding= nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn= nn.RNN(50, 64, batch_first=True)
    self.fc= nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question= self.embedding(question)
    hidde, final= self.rnn(embedded_question)
    output= self.fc(final.squeeze(0))
    return output

In [169]:
# example to understand the architecturre of of the RNN

x= nn.Embedding(324, embedding_dim=50)
y= nn.RNN(50, 64, batch_first=True)
z= nn.Linear(64, 324)


a= dataset[0][0].reshape(1, 6)

print("shape of a: ", a.shape)

b= x(a)

print("shape of b:", b.shape)

c, d= y(b)

print("shape of c:", c.shape)
print("shape of d: ", d.shape)



e= z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a:  torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d:  torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])


In [170]:
learning_rate= 0.001
epochs= 20

In [171]:
model=SimpleRNN(len(vocab))

# define loss function
criterion= nn.CrossEntropyLoss()

# define optimizer
optimizer= torch.optim.Adam(model.parameters(), lr= learning_rate)

In [172]:
# defining training loop

for epoch in range(epochs):
  total_loss= 0
  for question, answer in dataloader:
    optimizer.zero_grad()

    # forward pass
    output= model(question)

    # loss -> output shape (1, 324) -> (1)
    loss= criterion(output, answer[0])

    # backward pass- calculate the gradients
    loss.backward()

    # update the loss
    optimizer.step()

    total_loss= total_loss +loss.item()

  print(f'Epoch {epoch + 1}: Loss: {total_loss:.4f}')

Epoch 1: Loss: 526.4205
Epoch 2: Loss: 461.2269
Epoch 3: Loss: 382.8812
Epoch 4: Loss: 319.3019
Epoch 5: Loss: 266.9643
Epoch 6: Loss: 218.6181
Epoch 7: Loss: 174.9075
Epoch 8: Loss: 136.1406
Epoch 9: Loss: 104.8284
Epoch 10: Loss: 79.7591
Epoch 11: Loss: 61.8345
Epoch 12: Loss: 48.4764
Epoch 13: Loss: 38.4041
Epoch 14: Loss: 31.2608
Epoch 15: Loss: 25.7834
Epoch 16: Loss: 21.8204
Epoch 17: Loss: 18.3922
Epoch 18: Loss: 15.8978
Epoch 19: Loss: 13.6280
Epoch 20: Loss: 11.8597


In [173]:
def predict(model, question, threshold=0.5):
  # convert question to numbers
  numerical_question= text_to_indices(question, vocab)

  # tensor
  question_tensor= torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output= model(question_tensor)

  # convert logits to porbs
  probs= torch.nn.functional.softmax(output, dim=1)

  # finding the index of the max probility
  value, index= torch.max(probs, dim=1)

  if value < threshold:
    print("Bye")
  print(list(vocab.keys())[index])

In [174]:
predict(model, "What is the capital of?")

Bye
moscow


In [175]:
list(vocab.keys())[9]

'berlin'