In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name}")
else:
  print("GPU is not available")

GPU is available
Using GPU: <function get_device_name at 0x7b43a43f40e0>


### Creating Tensors

In [3]:
# using empty
a = torch.empty(2, 3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2, 3)

tensor([[0.2678, 0.1308, 0.8813],
        [0.8795, 0.2829, 0.3878]])

In [8]:
# manual seed-> reprocebility
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [9]:
# using tensors
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# arange
print("using arange -> ", torch.arange(0, 10))
# using linspace
print("using linspace->", torch.linspace(0, 10, 2))
# uisng eye
print("using eye -> ", torch.eye(5))
# using full
print("using full -> ", torch.full((3, 3,), 5))

using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace-> tensor([ 0., 10.])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensors Shapes

In [11]:
x = torch.tensor([[1, 2, 3],
                 [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [12]:
torch.empty_like(x)

tensor([[             250725,                   0, 8457593474420006765],
        [8459553839410930800, 7809644653626811246,                   0]])

In [13]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Data Types

In [15]:
# find data type
x.dtype

torch.int64

In [16]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [17]:
torch.tensor([2, 3, 4], dtype=torch.float64)

tensor([2., 3., 4.], dtype=torch.float64)

In [18]:
x = x.to(torch.float32)

In [19]:
torch.rand_like(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [20]:
# addition
x + 10

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [21]:
# subtraction
x - 10

tensor([[-9., -8., -7.],
        [-6., -5., -4.]])

In [22]:
# multiplication
x * -3

tensor([[ -3.,  -6.,  -9.],
        [-12., -15., -18.]])

In [23]:
# division
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [24]:
# int divison
(x * 100) // 3

tensor([[ 33.,  66., 100.],
        [133., 166., 200.]])

In [25]:
# add
a = torch.tensor([1, 23, 2])
b = torch.tensor([3, 12,  1])

a + b



tensor([ 4, 35,  3])

In [26]:
# subtraction
b - a

tensor([  2, -11,  -1])

In [27]:
# multiplication
a / b

tensor([0.3333, 1.9167, 2.0000])

In [28]:
# power
a ** b

tensor([                1, 21914624432020321,                 2])

In [29]:
c = torch.tensor([-1, -2, 3, -4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [31]:
d = torch.tensor([1.9, 2.6, 4.5, 7.2])
torch.round(d)

tensor([2., 3., 4., 7.])

In [32]:
torch.ceil(d)

tensor([2., 3., 5., 8.])

In [33]:
torch.floor(d)

tensor([1., 2., 4., 7.])

In [34]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.6000, 3.0000, 3.0000])

Reduction operation

In [35]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 4., 1.],
        [2., 5., 5.]])

In [36]:
# sum
torch.sum(e)

tensor(17.)

In [37]:
torch.sum(e, dim=0)

tensor([2., 9., 6.])

In [38]:
torch.sum(e, dim=1)

tensor([ 5., 12.])

In [39]:
torch.mean(e)

tensor(2.8333)

In [40]:
torch.mean(e, dim=0), torch.mean(e, dim=1)

(tensor([1.0000, 4.5000, 3.0000]), tensor([1.6667, 4.0000]))

In [41]:
torch.median(e)

tensor(2.)

In [42]:
torch.min(e)

tensor(0.)

In [43]:
torch.prod(e)

tensor(0.)

In [44]:
torch.std(e)

tensor(2.1370)

In [45]:
torch.var(e)

tensor(4.5667)

In [46]:
torch.argmax(e)

tensor(4)

In [47]:
torch.argmin(e)

tensor(0)

In [48]:
m1 = torch.randint(size=(2, 3), low= 0, high=10)
m2 = torch.randint(size=(3, 2),low=0, high=10)

In [49]:
torch.matmul(m1, m2)

tensor([[132, 156],
        [ 64,  54]])

In [50]:
v1= torch.tensor([2, 3])
v2 = torch.tensor([3, 4])

In [51]:
torch.dot(v1, v2)

tensor(18)

In [52]:
m1

tensor([[7, 6, 9],
        [6, 3, 1]])

In [53]:
torch.transpose(m1, 0, 1)

tensor([[7, 6],
        [6, 3],
        [9, 1]])

In [54]:
device = torch.device('cuda')
device

device(type='cuda')

In [55]:
torch.rand((2, 3), device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [56]:
a = torch.rand(2, 3)
b= a.to(device)

In [57]:
b + 5

tensor([[5.9516, 5.0753, 5.8860],
        [5.5832, 5.3376, 5.8090]], device='cuda:0')

In [58]:
import time
size= 1000
matrix_cpu1 =torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

# time on gpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on the GPU : {gpu_time:.4f}seconds")

Time on CPU: 0.0323 seconds
Time on the GPU : 0.1037seconds


Numpy and Pytorch

In [59]:
import numpy as np
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [60]:
b = a.numpy()

In [61]:
type(b)

numpy.ndarray

In [62]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [63]:
torch.from_numpy(c)

tensor([1, 2, 3])